use crate::plugin_runtime::host_api::PluginTableSchema;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OrmTarget {
    RustDiesel,
    RustSeaOrm,
    TypeScriptPrisma,
    TypeScriptTypeOrm,
    PythonSqlAlchemy2,
    PythonSqlAlchemy1,
}

impl OrmTarget {
    pub fn display_name(&self) -> &'static str {
        match self {
            OrmTarget::RustDiesel => "Rust (Diesel)",
            OrmTarget::RustSeaOrm => "Rust (SeaORM)",
            OrmTarget::TypeScriptPrisma => "TypeScript (Prisma)",
            OrmTarget::TypeScriptTypeOrm => "TypeScript (TypeORM)",
            OrmTarget::PythonSqlAlchemy2 => "Python (SQLAlchemy 2.0)",
            OrmTarget::PythonSqlAlchemy1 => "Python (SQLAlchemy 1.4)",
        }
    }

    pub fn language(&self) -> &'static str {
        match self {
            OrmTarget::RustDiesel | OrmTarget::RustSeaOrm => "rust",
            OrmTarget::TypeScriptPrisma => "prisma",
            OrmTarget::TypeScriptTypeOrm => "typescript",
            OrmTarget::PythonSqlAlchemy2 | OrmTarget::PythonSqlAlchemy1 => "python",
        }
    }
}

/// Helper to convert snake_case or table name to PascalCase for struct/class names
pub fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }
    if result.is_empty() {
        "Entity".to_string()
    } else {
        result
    }
}

/// Helper to convert string to snake_case
pub fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else if c == '-' || c == ' ' {
            result.push('_');
        } else {
            result.push(c);
        }
    }
    result
}

/// Generates ORM model code for the specified target
pub fn generate_orm_code(schema: &PluginTableSchema, target: OrmTarget) -> String {
    match target {
        OrmTarget::RustDiesel => generate_diesel(schema),
        OrmTarget::RustSeaOrm => generate_seaorm(schema),
        OrmTarget::TypeScriptPrisma => generate_prisma(schema),
        OrmTarget::TypeScriptTypeOrm => generate_typeorm(schema),
        OrmTarget::PythonSqlAlchemy2 => generate_sqlalchemy2(schema),
        OrmTarget::PythonSqlAlchemy1 => generate_sqlalchemy1(schema),
    }
}

// ---------------------------------------------------------------------------
// 1. Rust Diesel
// ---------------------------------------------------------------------------
fn generate_diesel(schema: &PluginTableSchema) -> String {
    let table_name = &schema.table_name;
    let struct_name = to_pascal_case(table_name);
    let mut out = String::new();

    out.push_str("// Generated by Tabular - Diesel ORM\n");
    out.push_str("use diesel::prelude::*;\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    // Diesel table! macro
    out.push_str(&format!("diesel::table! {{\n    {} (", table_name));
    let pk_cols: Vec<&str> = schema
        .columns
        .iter()
        .filter(|c| c.is_primary_key)
        .map(|c| c.name.as_str())
        .collect();
    if pk_cols.is_empty() {
        out.push_str("id");
    } else {
        out.push_str(&pk_cols.join(", "));
    }
    out.push_str(") {\n");

    for col in &schema.columns {
        let diesel_type = map_diesel_sql_type(&col.data_type, col.is_nullable);
        out.push_str(&format!("        {} -> {},\n", to_snake_case(&col.name), diesel_type));
    }
    out.push_str("    }\n}\n\n");

    // Rust Model Struct (Queryable)
    out.push_str(&format!(
        "#[derive(Queryable, Selectable, Insertable, Identifiable, Debug, Clone, Serialize, Deserialize)]\n\
         #[diesel(table_name = {})]\n\
         #[diesel(check_for_backend(diesel::pg::Pg))]\n\
         pub struct {} {{\n",
        table_name, struct_name
    ));

    for col in &schema.columns {
        let rust_type = map_rust_type(&col.data_type, col.is_nullable);
        out.push_str(&format!("    pub {}: {},\n", to_snake_case(&col.name), rust_type));
    }
    out.push_str("}\n\n");

    // Insertable NewModel Struct
    out.push_str(&format!(
        "#[derive(Insertable, Debug, Clone, Serialize, Deserialize)]\n\
         #[diesel(table_name = {})]\n\
         pub struct New{} {{\n",
        table_name, struct_name
    ));

    for col in &schema.columns {
        if col.is_auto_increment || (col.is_primary_key && col.default_value.is_some()) {
            continue;
        }
        let rust_type = map_rust_type(&col.data_type, col.is_nullable);
        out.push_str(&format!("    pub {}: {},\n", to_snake_case(&col.name), rust_type));
    }
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// 2. Rust SeaORM
// ---------------------------------------------------------------------------
fn generate_seaorm(schema: &PluginTableSchema) -> String {
    let table_name = &schema.table_name;
    let mut out = String::new();

    out.push_str("// Generated by Tabular - SeaORM Entity Model\n");
    out.push_str("use sea_orm::entity::prelude::*;\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    out.push_str(&format!(
        "#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]\n\
         #[sea_orm(table_name = \"{}\")]\n\
         pub struct Model {{\n",
        table_name
    ));

    for col in &schema.columns {
        let rust_type = map_rust_type(&col.data_type, col.is_nullable);
        let field_name = to_snake_case(&col.name);
        if col.is_primary_key {
            if col.is_auto_increment {
                out.push_str("    #[sea_orm(primary_key)]\n");
            } else {
                out.push_str("    #[sea_orm(primary_key, auto_increment = false)]\n");
            }
        }
        if col.name != field_name {
            out.push_str(&format!("    #[sea_orm(column_name = \"{}\")]\n", col.name));
        }
        out.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
    }
    out.push_str("}\n\n");

    out.push_str(
        "#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]\n\
         pub enum Relation {}\n\n\
         impl ActiveModelBehavior for ActiveModel {}\n",
    );

    out
}

// ---------------------------------------------------------------------------
// 3. TypeScript Prisma
// ---------------------------------------------------------------------------
fn generate_prisma(schema: &PluginTableSchema) -> String {
    let model_name = to_pascal_case(&schema.table_name);
    let mut out = String::new();

    out.push_str("// Generated by Tabular - Prisma Schema Model\n");
    out.push_str(&format!("model {} {{\n", model_name));

    for col in &schema.columns {
        let prisma_type = map_prisma_type(&col.data_type);
        let nullable_suffix = if col.is_nullable { "?" } else { "" };
        let mut attributes = Vec::new();

        if col.is_primary_key {
            attributes.push("@id".to_string());
            if col.is_auto_increment {
                attributes.push("@default(autoincrement())".to_string());
            }
        }
        if let Some(def) = &col.default_value {
            if !col.is_auto_increment && !def.is_empty() {
                if def.to_lowercase().contains("now") || def.to_lowercase().contains("current_timestamp") {
                    attributes.push("@default(now())".to_string());
                } else if let Ok(n) = def.parse::<i64>() {
                    attributes.push(format!("@default({})", n));
                } else if def.eq_ignore_ascii_case("true") || def.eq_ignore_ascii_case("false") {
                    attributes.push(format!("@default({})", def.to_lowercase()));
                }
            }
        }

        let attr_str = if attributes.is_empty() {
            String::new()
        } else {
            format!(" {}", attributes.join(" "))
        };

        out.push_str(&format!(
            "  {:16} {}{}{}\n",
            col.name, prisma_type, nullable_suffix, attr_str
        ));
    }

    if schema.table_name != model_name {
        out.push_str(&format!("\n  @@map(\"{}\")\n", schema.table_name));
    }
    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// 4. TypeScript TypeORM
// ---------------------------------------------------------------------------
fn generate_typeorm(schema: &PluginTableSchema) -> String {
    let class_name = to_pascal_case(&schema.table_name);
    let mut out = String::new();

    out.push_str("// Generated by Tabular - TypeORM Entity\n");
    out.push_str("import { Entity, PrimaryGeneratedColumn, PrimaryColumn, Column, CreateDateColumn, UpdateDateColumn } from \"typeorm\";\n\n");

    out.push_str(&format!("@Entity(\"{}\")\nexport class {} {{\n", schema.table_name, class_name));

    for col in &schema.columns {
        let ts_type = map_typescript_type(&col.data_type);
        let field_name = to_snake_case(&col.name);

        if col.is_primary_key {
            if col.is_auto_increment {
                out.push_str("  @PrimaryGeneratedColumn()\n");
            } else {
                out.push_str("  @PrimaryColumn()\n");
            }
        } else if col.is_nullable {
            out.push_str(&format!("  @Column({{ nullable: true, name: \"{}\" }})\n", col.name));
        } else {
            out.push_str(&format!("  @Column({{ name: \"{}\" }})\n", col.name));
        }

        let optional = if col.is_nullable { "?" } else { "" };
        out.push_str(&format!("  {}{}: {};\n\n", field_name, optional, ts_type));
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// 5. Python SQLAlchemy 2.0
// ---------------------------------------------------------------------------
fn generate_sqlalchemy2(schema: &PluginTableSchema) -> String {
    let class_name = to_pascal_case(&schema.table_name);
    let mut out = String::new();

    out.push_str("# Generated by Tabular - SQLAlchemy 2.0 Model\n");
    out.push_str("from typing import Optional\n");
    out.push_str("from datetime import datetime, date, time\n");
    out.push_str("from sqlalchemy import String, Integer, BigInteger, Float, Boolean, DateTime, Date, Time, Text\n");
    out.push_str("from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column\n\n");
    out.push_str("class Base(DeclarativeBase):\n    pass\n\n");

    out.push_str(&format!("class {}(Base):\n", class_name));
    out.push_str(&format!("    __tablename__ = \"{}\"\n\n", schema.table_name));

    for col in &schema.columns {
        let py_type = map_python_type(&col.data_type);
        let field_name = to_snake_case(&col.name);
        let mut col_args = Vec::new();

        if col.is_primary_key {
            col_args.push("primary_key=True".to_string());
        }
        if col.is_auto_increment {
            col_args.push("autoincrement=True".to_string());
        }
        if col.name != field_name {
            col_args.push(format!("name=\"{}\"", col.name));
        }

        let arg_str = if col_args.is_empty() {
            String::new()
        } else {
            col_args.join(", ")
        };

        if col.is_nullable {
            out.push_str(&format!(
                "    {}: Mapped[Optional[{}]] = mapped_column({})\n",
                field_name, py_type, arg_str
            ));
        } else {
            out.push_str(&format!(
                "    {}: Mapped[{}] = mapped_column({})\n",
                field_name, py_type, arg_str
            ));
        }
    }

    out
}

// ---------------------------------------------------------------------------
// 6. Python SQLAlchemy 1.4 (Classic)
// ---------------------------------------------------------------------------
fn generate_sqlalchemy1(schema: &PluginTableSchema) -> String {
    let class_name = to_pascal_case(&schema.table_name);
    let mut out = String::new();

    out.push_str("# Generated by Tabular - SQLAlchemy 1.4 (Classic)\n");
    out.push_str("from sqlalchemy import Column, Integer, BigInteger, String, Float, Boolean, DateTime, Date, Time, Text\n");
    out.push_str("from sqlalchemy.ext.declarative import declarative_base\n\n");
    out.push_str("Base = declarative_base()\n\n");

    out.push_str(&format!("class {}(Base):\n", class_name));
    out.push_str(&format!("    __tablename__ = \"{}\"\n\n", schema.table_name));

    for col in &schema.columns {
        let sqla_type = map_sqla_column_type(&col.data_type);
        let field_name = to_snake_case(&col.name);
        let mut col_args = vec![sqla_type];

        if col.is_primary_key {
            col_args.push("primary_key=True");
        }
        if !col.is_nullable {
            col_args.push("nullable=False");
        }

        out.push_str(&format!(
            "    {} = Column({})\n",
            field_name,
            col_args.join(", ")
        ));
    }

    out
}

// ---------------------------------------------------------------------------
// Type Mapping Helpers
// ---------------------------------------------------------------------------
fn map_diesel_sql_type(raw_type: &str, nullable: bool) -> String {
    let lower = raw_type.to_lowercase();
    let base = if lower.contains("bigint") || lower.contains("int8") {
        "BigInt"
    } else if lower.contains("smallint") || lower.contains("int2") {
        "SmallInt"
    } else if lower.contains("tinyint") || lower.contains("int1") {
        "TinyInt"
    } else if lower.contains("int") || lower.contains("serial") {
        "Integer"
    } else if lower.contains("bool") {
        "Bool"
    } else if lower.contains("double") || lower.contains("float8") {
        "Double"
    } else if lower.contains("float") || lower.contains("real") || lower.contains("float4") {
        "Float"
    } else if lower.contains("timestamp") || lower.contains("datetime") {
        "Timestamp"
    } else if lower.contains("date") {
        "Date"
    } else if lower.contains("time") {
        "Time"
    } else if lower.contains("json") {
        "Jsonb"
    } else if lower.contains("blob") || lower.contains("bytea") || lower.contains("binary") {
        "Binary"
    } else {
        "Text"
    };

    if nullable {
        format!("Nullable<{}>", base)
    } else {
        base.to_string()
    }
}

fn map_rust_type(raw_type: &str, nullable: bool) -> String {
    let lower = raw_type.to_lowercase();
    let base = if lower.contains("bigint") || lower.contains("int8") {
        "i64"
    } else if lower.contains("smallint") || lower.contains("int2") {
        "i16"
    } else if lower.contains("tinyint") || lower.contains("int1") {
        "i8"
    } else if lower.contains("int") || lower.contains("serial") {
        "i32"
    } else if lower.contains("bool") {
        "bool"
    } else if lower.contains("double") || lower.contains("float8") {
        "f64"
    } else if lower.contains("float") || lower.contains("real") || lower.contains("float4") {
        "f32"
    } else if lower.contains("timestamp") || lower.contains("datetime") {
        "chrono::NaiveDateTime"
    } else if lower.contains("date") {
        "chrono::NaiveDate"
    } else if lower.contains("time") {
        "chrono::NaiveTime"
    } else if lower.contains("json") {
        "serde_json::Value"
    } else if lower.contains("blob") || lower.contains("bytea") || lower.contains("binary") {
        "Vec<u8>"
    } else {
        "String"
    };

    if nullable {
        format!("Option<{}>", base)
    } else {
        base.to_string()
    }
}

fn map_prisma_type(raw_type: &str) -> &'static str {
    let lower = raw_type.to_lowercase();
    if lower.contains("bigint") || lower.contains("int8") {
        "BigInt"
    } else if lower.contains("int") || lower.contains("serial") || lower.contains("smallint") {
        "Int"
    } else if lower.contains("bool") {
        "Boolean"
    } else if lower.contains("double") || lower.contains("float") || lower.contains("real") {
        "Float"
    } else if lower.contains("decimal") || lower.contains("numeric") {
        "Decimal"
    } else if lower.contains("timestamp") || lower.contains("datetime") || lower.contains("date") {
        "DateTime"
    } else if lower.contains("json") {
        "Json"
    } else if lower.contains("blob") || lower.contains("bytea") || lower.contains("binary") {
        "Bytes"
    } else {
        "String"
    }
}

fn map_typescript_type(raw_type: &str) -> &'static str {
    let lower = raw_type.to_lowercase();
    if lower.contains("int") || lower.contains("float") || lower.contains("double") || lower.contains("decimal") || lower.contains("numeric") || lower.contains("serial") {
        "number"
    } else if lower.contains("bool") {
        "boolean"
    } else if lower.contains("timestamp") || lower.contains("datetime") || lower.contains("date") {
        "Date"
    } else if lower.contains("json") {
        "Record<string, any>"
    } else if lower.contains("blob") || lower.contains("bytea") || lower.contains("binary") {
        "Buffer"
    } else {
        "string"
    }
}

fn map_python_type(raw_type: &str) -> &'static str {
    let lower = raw_type.to_lowercase();
    if lower.contains("bigint") || lower.contains("int8") {
        "int"
    } else if lower.contains("int") || lower.contains("serial") || lower.contains("smallint") {
        "int"
    } else if lower.contains("bool") {
        "bool"
    } else if lower.contains("double") || lower.contains("float") || lower.contains("real") || lower.contains("decimal") {
        "float"
    } else if lower.contains("timestamp") || lower.contains("datetime") {
        "datetime"
    } else if lower.contains("date") {
        "date"
    } else if lower.contains("time") {
        "time"
    } else if lower.contains("json") {
        "dict"
    } else if lower.contains("blob") || lower.contains("bytea") || lower.contains("binary") {
        "bytes"
    } else {
        "str"
    }
}

fn map_sqla_column_type(raw_type: &str) -> &'static str {
    let lower = raw_type.to_lowercase();
    if lower.contains("bigint") || lower.contains("int8") {
        "BigInteger"
    } else if lower.contains("int") || lower.contains("serial") || lower.contains("smallint") {
        "Integer"
    } else if lower.contains("bool") {
        "Boolean"
    } else if lower.contains("double") || lower.contains("float") || lower.contains("real") || lower.contains("decimal") {
        "Float"
    } else if lower.contains("timestamp") || lower.contains("datetime") {
        "DateTime"
    } else if lower.contains("date") {
        "Date"
    } else if lower.contains("time") {
        "Time"
    } else if lower.contains("text") {
        "Text"
    } else {
        "String(255)"
    }
}

/// WebAssembly Text (WAT) source code for the starter ORM Models plugin
pub const WAT_ORM_STARTER: &str = r#"(module
  (import "env" "tabular_get_table_schema_len" (func $get_schema_len (result i32)))
  (import "env" "tabular_get_table_schema_data" (func $get_schema_data (param i32 i32) (result i32)))
  (import "env" "tabular_export_data" (func $export_data (param i32 i32 i32 i32) (result i32)))
  (import "env" "tabular_log" (func $log (param i32 i32 i32) (result i32)))
  (import "env" "tabular_set_result" (func $set_result (param i32 i32) (result i32)))

  (memory (export "memory") 1)

  (data (i32.const 1024) "prisma")
  (data (i32.const 1040) "rust")
  (data (i32.const 1056) "[ORM Plugin] Generating ORM Entity Models from Database Schema...")
  (data (i32.const 1200) "// Generated by Wasm ORM Plugin\nmodel Entity {\n  id Int @id @default(autoincrement())\n  created_at DateTime @default(now())\n}\n")

  (func (export "tabular_main")
    (call $log (i32.const 1) (i32.const 1056) (i32.const 65))
    drop

    (call $export_data (i32.const 1024) (i32.const 6) (i32.const 1200) (i32.const 105))
    drop

    (call $set_result (i32.const 1200) (i32.const 105))
    drop
  )
)
"#;
