use crate::plugin_runtime::host_api::{PluginSelectionData, PluginTableSchema};

/// Generates a standalone DuckDB SQL script for loading, querying, and exporting data to Parquet
pub fn generate_duckdb_script(
    schema: &PluginTableSchema,
    data: Option<&PluginSelectionData>,
    output_parquet_path: Option<&str>,
) -> String {
    let table_name = &schema.table_name;
    let target_parquet = output_parquet_path.unwrap_or("output.parquet");

    let mut sql = String::new();
    sql.push_str(&format!(
        "-- ====================================================================\n\
         -- DuckDB & Apache Parquet Automation Script for Table: {}\n\
         -- Generated by Tabular Plugin Extensibility Engine\n\
         -- ====================================================================\n\n",
        table_name
    ));

    // DuckDB Schema creation
    sql.push_str(&format!("-- 1. Create In-Memory DuckDB Table Schema\nCREATE OR REPLACE TABLE \"{}\" (\n", table_name));

    let col_defs: Vec<String> = schema
        .columns
        .iter()
        .map(|col| {
            let duckdb_type = map_to_duckdb_type(&col.data_type);
            let not_null = if !col.is_nullable { " NOT NULL" } else { "" };
            let pk = if col.is_primary_key { " PRIMARY KEY" } else { "" };
            format!("    \"{}\" {}{}{}", col.name, duckdb_type, not_null, pk)
        })
        .collect();

    sql.push_str(&col_defs.join(",\n"));
    sql.push_str("\n);\n\n");

    // Sample/Selected rows INSERTs for DuckDB if data provided
    if let Some(sel) = data {
        if !sel.rows.is_empty() {
            sql.push_str("-- 2. Insert Selected Data into DuckDB\n");
            let col_list = sel
                .headers
                .iter()
                .map(|h| format!("\"{}\"", h))
                .collect::<Vec<_>>()
                .join(", ");

            for chunk in sel.rows.chunks(100) {
                sql.push_str(&format!("INSERT INTO \"{}\" ({}) VALUES\n", table_name, col_list));
                let rows: Vec<String> = chunk
                    .iter()
                    .map(|r| {
                        let vals: Vec<String> = r
                            .iter()
                            .map(|v| {
                                if v.is_empty() || v.eq_ignore_ascii_case("null") {
                                    "NULL".to_string()
                                } else if v.parse::<i64>().is_ok() || v.parse::<f64>().is_ok() {
                                    v.clone()
                                } else {
                                    format!("'{}'", v.replace('\'', "''"))
                                }
                            })
                            .collect();
                        format!("    ({})", vals.join(", "))
                    })
                    .collect();
                sql.push_str(&rows.join(",\n"));
                sql.push_str(";\n\n");
            }
        }
    }

    // Export to Apache Parquet with compression
    sql.push_str(&format!(
        "-- 3. Export DuckDB Table to Optimized Apache Parquet (Snappy Compressed)\n\
         COPY \"{}\" TO '{}' (FORMAT PARQUET, COMPRESSION 'SNAPPY', ROW_GROUP_SIZE 100000);\n\n",
        table_name, target_parquet
    ));

    // DuckDB Direct Querying Parquet Example
    sql.push_str(&format!(
        "-- 4. Direct Analytics Query on Parquet File (Zero Copy)\n\
         SELECT * FROM read_parquet('{}') LIMIT 10;\n",
        target_parquet
    ));

    sql
}

/// Map generic SQL data types to DuckDB / Parquet physical types
pub fn map_to_duckdb_type(raw_type: &str) -> &'static str {
    let lower = raw_type.to_lowercase();
    if lower.contains("bigint") || lower.contains("int8") {
        "BIGINT"
    } else if lower.contains("smallint") || lower.contains("int2") {
        "SMALLINT"
    } else if lower.contains("tinyint") || lower.contains("int1") {
        "TINYINT"
    } else if lower.contains("int") || lower.contains("serial") {
        "INTEGER"
    } else if lower.contains("bool") {
        "BOOLEAN"
    } else if lower.contains("double") || lower.contains("float8") {
        "DOUBLE"
    } else if lower.contains("float") || lower.contains("real") || lower.contains("float4") {
        "FLOAT"
    } else if lower.contains("decimal") || lower.contains("numeric") {
        "DECIMAL(18, 4)"
    } else if lower.contains("timestamp") || lower.contains("datetime") {
        "TIMESTAMP"
    } else if lower.contains("date") {
        "DATE"
    } else if lower.contains("time") {
        "TIME"
    } else if lower.contains("json") || lower.contains("jsonb") {
        "JSON"
    } else if lower.contains("blob") || lower.contains("bytea") || lower.contains("binary") {
        "BLOB"
    } else if lower.contains("uuid") {
        "UUID"
    } else {
        "VARCHAR"
    }
}

/// WebAssembly Text (WAT) source code for the starter Parquet/DuckDB plugin
pub const WAT_PARQUET_STARTER: &str = r#"(module
  (import "env" "tabular_get_table_schema_len" (func $get_schema_len (result i32)))
  (import "env" "tabular_get_table_schema_data" (func $get_schema_data (param i32 i32) (result i32)))
  (import "env" "tabular_export_data" (func $export_data (param i32 i32 i32 i32) (result i32)))
  (import "env" "tabular_log" (func $log (param i32 i32 i32) (result i32)))
  (import "env" "tabular_set_result" (func $set_result (param i32 i32) (result i32)))

  (memory (export "memory") 1)

  ;; Pre-allocated strings in linear memory
  (data (i32.const 1024) "parquet")
  (data (i32.const 1040) "duckdb")
  (data (i32.const 1056) "[Parquet Plugin] Analyzing table schema and building DuckDB / Parquet pipeline...")
  (data (i32.const 1200) "-- DuckDB Parquet Export Generated via Wasm Plugin\nCOPY (SELECT * FROM current_table) TO 'export.parquet' (FORMAT PARQUET, COMPRESSION 'SNAPPY');\n")

  (func (export "tabular_main")
    ;; Log starting message
    (call $log (i32.const 1) (i32.const 1056) (i32.const 82))
    drop

    ;; Export DuckDB script
    (call $export_data (i32.const 1040) (i32.const 6) (i32.const 1200) (i32.const 140))
    drop

    ;; Set result message
    (call $set_result (i32.const 1200) (i32.const 140))
    drop
  )
)
"#;
